### ISSUE TITLE
Twitter communication thread of CuratedCellAtlas R and Py

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/CuratedAtlasQueryR#53]
Hello APP team,

here we are defining what is the content, images and text, or the Twitter thread we want to post. I think that, when we make this app public, we should have synergies in communicating this App, still first of it's kind, to get the community excited.

Some points for thought

- do we want to mention/tag funding bodies
- do we want to mention/tag institutions
- which language
- which content
- which figures
- do we  produce a github webpage/post in some blog or not
- which hashtags (I'm not a twitter expert)

**Comment by mtmorgan** [comment]
@stemangiola would be great to acknowledge the Silicon Valley Foundation CZF2019-002443 in the read me, and in `Authors@R` using `role = "fnd"` (from the help page `?person`)

**Comment by vjcitn** [comment]
Along with NIH NHGRI 5U24HG004059-18 (Bioconductor core funding)

**Comment by stemangiola** [comment]
Sure,

-  I will put funding bodies in the README
- Are you happy to be added in the Authors@R? In this case with which role?
- Should I add logos of the CZI, SVF, Bioconductor in the header of README next to our logo?

**Comment by stemangiola** [comment]
Created the pull request above.

**Comment by stemangiola** [comment]
Twitter thread:

[1/n]
We are glad to launch `CuratedCellAtlasR`, an API for the programmatic exploration and retrieval of the harmonised, curated and reannotated #CELLxGENE #singlecell human #atlas. Data can be retrieved at cell, sample, or dataset levels based on filtering criteria.

[At Github](https://github.com/stemangiola/CuratedAtlasQueryR), soon @ @Bioconductor

<img width="429" alt="image" src="https://user-images.githubusercontent.com/7232890/218939482-ee9626cd-5ca8-4fb5-8023-fb315e06bc00.png">

[tag people, @Bioconductor, Michael Milton, Martin Morgan, Vincent Carey, Tony Papenfuss]

[2/n]
Step 1: Explore the integrated cell, sample and dataset metadata on-disk. The curated atlas includes ~30M cells from  344 studies across 40 tissues. We provide raw abundances and counts per million. 

`get_metadata()`

![image](https://user-images.githubusercontent.com/7232890/218933732-64168a45-aff0-4ca4-9fc4-265be4ce4262.png)

[3/n]

Step 2: Filter the cells of interest using `tidyverse`

<img width="485" alt="image" src="https://user-images.githubusercontent.com/7232890/218941572-6950b5a1-7023-4126-8d42-e88b3f32039e.png">

[4/n]

Step 3: Collect the raw gene abundance and counts-per-million counts using HDF5 on-disk containers

![image](https://user-images.githubusercontent.com/7232890/218941342-32c8eef9-7d9e-438b-b89c-8037e630f020.png)
