### ISSUE TITLE
Prepare users for 36GB download

### ISSUE THREAD

**Issue by vjcitn** [stemangiola/CuratedAtlasQueryR#60]
The download seems fast enough, but people may benefit from knowing that they will receive 36GB of data.  I'd suggest making the download function conditional on a positive response to a query on whether they want to proceed.

**Comment by multimeric** [comment]
@stemangiola would you rather this be a message printed to console, or an interactive prompt using `utils::menu`?

**Comment by stemangiola** [comment]
For < 1Gb I would prefer a message rather than an interactive question. If people want can cancer installation or remove package.

**Comment by multimeric** [comment]
What about with the count data itself?

**Comment by stemangiola** [comment]
We can message N files will be downloaded. We don't need confirmation I believe.

**Comment by stemangiola** [comment]
So this is still an action point? OK. I'll reopen.

**Comment by multimeric** [comment]
I think so. I'll get to it if/when I have time.

**Comment by multimeric** [comment]
I guess this is tricky to do correctly. Calculating the total size of the download without actually doing the download would be a lot of work. And if you don't want an interactive prompt, then there's probably nothing to really do here.

**Comment by stemangiola** [comment]
In the data upload automation, could we `du` the file_id_db, and add a file_id_size column, that we can get and sum upon a user query?

**Comment by multimeric** [comment]
That's a good idea, it would be not too hard to implement. Do you think it's worth doing?

**Comment by stemangiola** [comment]
This could be couple of hours work, and it would add a layer of fairness to the API.

I think a simple message("XXX Mb will be downloaded")

We already have a function that detects the cache, so the cache file_id_db can be filtered out the sum

**Comment by multimeric** [comment]
I can probably do this without adding to the metadata, using HTTP `HEAD` requests.

**Comment by stemangiola** [comment]
not sure what that means; but the less invasive the procedure is, the better. :)
