### ISSUE TITLE
`_cell` must be size 202 or 1, not 157.

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/CuratedAtlasQueryR#78]
I get this error with the new version.

```r
> get_metadata() |> 
+     
+     # Filter and subset
+     filter(cell_type_harmonised=="cdc") |> 
+     select(`_cell`, file_id_db, dataset_id, tissue_harmonised) |> 
+     # Get counts per million for NCAM1 gene 
+     get_SingleCellExperiment(assays = "cpm", features = "HLA-A") 
ℹ Realising metadata.
ℹ Synchronising files
ℹ Reading files.
Error in `map2()`:
ℹ In index: 1.
ℹ With name: cpm.
Caused by error in `dplyr::summarise()`:
ℹ In argument: `sces = list(...)`.
Caused by error in `mutate()`:
ℹ In argument: `_cell = new_cellnames`.
Caused by error:
! `_cell` must be size 202 or 1, not 157.
Run `rlang::last_error()` to see where the error occurred.
Warning messages:
1: Connection is garbage-collected, use dbDisconnect() to avoid this. 
2: Database is garbage-collected, use dbDisconnect(con, shutdown=TRUE) or duckdb::duckdb_shutdown(drv) to avoid this. 
```

**Comment by multimeric** [comment]
Can be reproduced using:
```R
get_metadata() |> filter(cell_type_harmonised=="cdc") |> get_SingleCellExperiment(assays = "cpm") 
```

**Comment by multimeric** [comment]
I think this is due to the fact that the number of cells actually in this file is less than the number of cells your metadata file believes are in the file: `/vast/scratch/users/milton.m/cache/R/CuratedAtlasQueryR/0.2/cpm/c5a05f23f9784a3be3bfa651198a48eb`

To demonstrate:
```R
> loadHDF5SummarizedExperiment("/vast/scratch/users/milton.m/cache/R/CuratedAtlasQueryR/0.2/cpm/c5a05f23f9784a3be3bfa651198a48eb") |> colnames() |> length()
[1] 241813
> get_metadata() |> dplyr::filter(file_id_db == "c5a05f23f9784a3be3bfa651198a48eb") |> dplyr::pull(`_cell`) |> unique() |> length()
[1] 307429
```

**Comment by multimeric** [comment]
Not sure what the package should do in this scenario.

**Comment by stemangiola** [comment]
Yes I have to try to solve this. I have to find the reason of this mismatch.

**Comment by stemangiola** [comment]
@multimeric so I found the reason. For the DB files, I was filtering weird cells before de-logging. Now I have updated the code, but python-R interaction decided to go crazy during the weekend. 

Because the DB2 redoing will take couple of days, could we allow smaller count matrices than metadata for two days, while we solve this in the back end?

Again the goal is to release tomorrow 4PM and fix bug max by Wednesday, IT support allowing (who I hope will help to solve my issue quickly)

**Comment by multimeric** [comment]
> could we allow smaller count matrices than metadata for two days

I don't understand what you mean.

**Comment by stemangiola** [comment]
Can we patch this in the r package for now, so an object is returned anyway?

**Comment by multimeric** [comment]
Oh, I see. Yes I can look into that. Maybe with a warning just so we don't forget about it?

**Comment by stemangiola** [comment]
OK the warning might be "some cells were filtered out because of extremely low counts."

Of course the goal is in 2 max 3 days to update some DB2 files

**Comment by stemangiola** [comment]
> ```r
> loadHDF5SummarizedExperiment("/vast/scratch/users/milton.m/cache/R/CuratedAtlasQueryR/0.2/cpm/c5a05f23f9784a3be3bfa651198a48eb") |> colnames() |> length()
> ```

Now I get 

```r
> loadHDF5SummarizedExperiment("/vast/projects/cellxgene_curated/splitted_DB2_data_0.2.1/c5a05f23f9784a3be3bfa651198a48eb") |> colnames() |> leng[1] 

307429
```
