### ISSUE TITLE
README inconsistencies - Visualise gene Transcription section

### ISSUE THREAD

**Issue by federiva** [stemangiola/CuratedAtlasQueryR#91]
Hey there! 
I've noted a few inconsistencies in the README, specifically in the [Visualise Transcription section](https://github.com/stemangiola/CuratedAtlasQueryR#visualise-gene-transcription)

**Issue 1**
Intro text starts with `We can gather all natural killer cells and plot the distribution of CD56 (NCAM1) across all tissues` but immediately proceeds with an example with `CD14` cells and `HLA`
![image](https://user-images.githubusercontent.com/25372718/221188873-0a51ca95-f2f6-4320-a80e-9809597427ec.png)
 
**Issue 2**
Comment in the same code block about CD14-HLA is mentioning NCAM instead of HLA-1
![image](https://user-images.githubusercontent.com/25372718/221189454-944bb0ae-a98d-4d9f-ae7c-88d7c9f232b1.png)

**Issue 3**
In the second plot NK-NCAM the title and axis labels are still mentioning CD14-HLA. And also missing the cell type
![image](https://user-images.githubusercontent.com/25372718/221189887-59e8d0a6-5b65-4061-92a1-34019c364f62.png)

_Suggestion & Opinion_
Maybe you can add some of these examples under `inst/examples` and add a simple helper function (e.g. `run_atlas_example("cd14_hla")` to run them interactively?  IMHO this is also suuuper helpful when initially working with some packages

**_Thanks for your work!!_**

**Comment by stemangiola** [comment]
Thanks for that!
