### ISSUE TITLE
"Author Categories" accessible?

### ISSUE THREAD

**Issue by jgilis** [stemangiola/CuratedAtlasQueryR#95]
Hi developers,

Quick question: is it possible to obtain the cell metadata that are flagged as "Author categories" on the cellxgene website using `CuratedAtlasQueryR`?

An example, I am looking at [this](https://cellxgene.cziscience.com/e/c7775e88-49bf-4ba2-a03b-93f00447c958.cxg/) dataset on the cellxgene website. I can obtain a subset of cells e.g. by

```{r}
sce_sub <- metadata |>
    dplyr::filter(
        name == "Single-cell multi-omics analysis of the immune response in COVID-19",
        cell_type == "plasmablast",
        disease %in% c("COVID-19",
                       "normal")
    ) |>
    get_SingleCellExperiment()
```

When looking at the `colData`, I don't seem to have any of the information that is flagged on the website as "Author Categories".  Some of which in this case may be invaluable (smoking status, outcome, days from onset, ...).

How can I obtain these variables for my selected cells?

Very nice package by the way, congrats!

**Comment by stemangiola** [comment]
Hello @jgilis,

yes, very important. I thought about dataset-specific metadata, and for the moment my suggestion (that I might document in the README and vignette) is to use `cellxgenedp` to query for that dataset and get the full (non-harmonised) metadata from each dataset.

**Comment by jgilis** [comment]
Hi @stemangiola,

Thank you far the fast reply @stemangiola! I will use `cellxgenedp` for that.

I wonder if in the future you envision to do it via `CuratedAtlasQueryR` directly. I didn't really look into how it exactly it is implemented, but I guess the challenge is also a conceptual one in the sense that you may not want to import non-curated info with the package, which kind of beats the purpose. 

Just out of curiosity, would it be technically possible to e.g. dump all dataset-specific metadata as a list (1 list per dataset)?

**Comment by stemangiola** [comment]
Yes, trying to append it to the same table is challenging; many columns have the same name but different classes, put output a list would be easier. I will put it as a feature request.

**Comment by jgilis** [comment]
Cool thanks! 💯
